name: "Run Cypress tests"

on: [push]

jobs:
  run_e2e_tests:
    # if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
      - name: Upload videos
        if: always() # / if: failure() <- more suitable for production
        uses: actions/upload-artifact@v1
        with:
          name: cypress-videos
          path: cypress/videos

      # - name: Run Cypress
      #   uses: cypress-io/github-action@v2
      #   env:
      #     CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
      #     CYPRESS_SECRET: ${{ secrets.CYPRESS_SECRET }}
      #     CYPRESS_RETRIES: 1
      # - uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     retention-days: 1
      #     path: |
      #       cypress/videos
